#pragma once

enum class AudioId
{
    AMBIENT = 0,
    PROJECTILE_BASIC,
    PROJECTILE_LASER,
    PROJECTILE_MISSILE,
    PROJECTILE_EXPLOSION_DEBRIS,
    PROJECTILE_ALIEN_BASIC,
    UPGRADEBOX_HEALTH,
    UPGRADEBOX_WEAPON,
    DEATH_PLAYER,
};